### PR TITLE
feat(order): Allow multiple orders per coordinator and restaurant

### LINKED ISSUE #15: Cannot create multiple orders for same restaurant
There is a unique constraint forbidding to create a second order with the same coordinator name for the same restaurant.

bildschirmfoto von 2018-03-01 18-12-21

In general I appreciate the idea to encourage a more diversified diet. But It would be better not to enforce it in such a strict way ;)

### PR DESCRIPTION
**Pull request by YtvwlD**
To archieve this, UUIDs are used as slugs.
This closes #15.

Tests are missing, yet. I'll add them (hopefully) later today.

### CODE REVIEW

**Comment by YtvwlD** [comment]
Now, that the slugs are random, various tests are failing (at least I think that's the reason).
I'll have to investigate this later - but probably not today.

**Comment by msteinhoff** [comment]
> Now, that the slugs are random, various tests are failing (at least I think that's the reason).

I analyzed the bug last sunday and the fix already Works On My Machine [tm]. In the original implementation, the slug field is updated each time `save()` is called, and the value is deterministic as long as coordinator and restaurant does not change:

```python
self.slug = slugify("{} {}".format(self.coordinator, self.restaurant_name))	
```

With this change:

```python
self.slug = str(uuid4())
```

A new UUID is generated everytime the model is saved, which breaks all the tests.

Solution: Do not set slug in save method and use https://docs.djangoproject.com/en/2.2/ref/models/fields/#uuidfield instead. I already created a fix but its not yet committed.

**Comment by YtvwlD** [comment]
Oh.
The slug should stay the same when editing an order, of course.

**Comment by YtvwlD** [comment]
A simple fix is to replace

```python
self.slug = str(uuid4())
```

with

```python
if not self.slug:
    self.slug = str(uuid4())
```

**Pull request merged**
